### ISSUE TITLE
Add a genre filter

### ISSUE THREAD

**Issue by ghost** [joshuachu007/jTunes#11]
We have getArtists, getAlbums, and getSongs.

How about getGenres?

**Comment by ahmed3m** [comment]
getGenres is really inside the constructor. 
getArtists gets the genreID, and calls printArtists. 
getAlbums gets the artistID and the genreID, and calls printAlbums.
getSongs will get the albumID, and calls printSongs.

So they are really all dependent on the previous choice. There's no option to jump back or forth. For the GUI, we can add that functionality but I'd need to know how the buttons work and it could be a bit tricky.
